import Head from 'next/head'
// import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { SlateTextEditor } from '@/components/slate-text-editor'

export default function Home() {
  return (
    <>
      <Head>
        <title>SlateJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.editorContainer}>
          <SlateTextEditor />
        </div>
      </main>
    </>
  )
}